name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        run: |
          sudo apt-get -y update && sudo apt-get -yqq install build-essential texlive-full texlive-latex-extra
          cd templates/latex-thesis
          make all
      - uses: actions/upload-artifact@master
        with:
          name: moonproject
          path: templates/latex-thesis/moonproject.pdf
